// SPDX-License-Identifier: GPL-3.0-or-later

import Foundation

public enum WindowPlacement: String, CaseIterable, Codable, Sendable {
    case left = "left"
    case right = "right"
    case top = "top"
    case bottom = "bottom"
    case center = "center"
    case center80 = "center-80"
    case fill = "fill"
    case maximizeWidth = "maximize-width"
    case maximizeHeight = "maximize-height"
    case topLeft = "top-left"
    case topRight = "top-right"
    case bottomLeft = "bottom-left"
    case bottomRight = "bottom-right"
    case firstThird = "first-third"
    case centerThird = "center-third"
    case lastThird = "last-third"
    case firstTwoThirds = "first-two-thirds"
    case centerTwoThirds = "center-two-thirds"
    case lastTwoThirds = "last-two-thirds"
    case firstFourth = "first-fourth"
    case secondFourth = "second-fourth"
    case thirdFourth = "third-fourth"
    case lastFourth = "last-fourth"
    case firstThreeFourths = "first-three-fourths"
    case centerThreeFourths = "center-three-fourths"
    case lastThreeFourths = "last-three-fourths"
    case topLeftSixth = "top-left-sixth"
    case topCenterSixth = "top-center-sixth"
    case topRightSixth = "top-right-sixth"
    case bottomLeftSixth = "bottom-left-sixth"
    case bottomCenterSixth = "bottom-center-sixth"
    case bottomRightSixth = "bottom-right-sixth"
    case increaseSize10 = "increase-size-10"
    case decreaseSize10 = "decrease-size-10"
    case increaseLeft10 = "increase-left-10"
    case increaseRight10 = "increase-right-10"
    case increaseTop10 = "increase-top-10"
    case increaseBottom10 = "increase-bottom-10"
    case decreaseLeft10 = "decrease-left-10"
    case decreaseRight10 = "decrease-right-10"
    case decreaseTop10 = "decrease-top-10"
    case decreaseBottom10 = "decrease-bottom-10"
    case moveUp10 = "move-up-10"
    case moveDown10 = "move-down-10"
    case moveLeft10 = "move-left-10"
    case moveRight10 = "move-right-10"

    public var displayName: String {
        switch self {
        case .left: "Left Half"
        case .right: "Right Half"
        case .top: "Top Half"
        case .bottom: "Bottom Half"
        case .center: "Center"
        case .center80: "Almost Maximize"
        case .fill: "Maximize"
        case .maximizeWidth: "Maximize Width"
        case .maximizeHeight: "Maximize Height"
        case .topLeft: "Top Left"
        case .topRight: "Top Right"
        case .bottomLeft: "Bottom Left"
        case .bottomRight: "Bottom Right"
        case .firstThird: "First Third"
        case .centerThird: "Center Third"
        case .lastThird: "Last Third"
        case .firstTwoThirds: "First Two Thirds"
        case .centerTwoThirds: "Center Two Thirds"
        case .lastTwoThirds: "Last Two Thirds"
        case .firstFourth: "First Fourth"
        case .secondFourth: "Second Fourth"
        case .thirdFourth: "Third Fourth"
        case .lastFourth: "Last Fourth"
        case .firstThreeFourths: "First Three Fourths"
        case .centerThreeFourths: "Center Three Fourths"
        case .lastThreeFourths: "Last Three Fourths"
        case .topLeftSixth: "Top Left Sixth"
        case .topCenterSixth: "Top Center Sixth"
        case .topRightSixth: "Top Right Sixth"
        case .bottomLeftSixth: "Bottom Left Sixth"
        case .bottomCenterSixth: "Bottom Center Sixth"
        case .bottomRightSixth: "Bottom Right Sixth"
        case .increaseSize10: "Increase Size by 10%"
        case .decreaseSize10: "Decrease Size by 10%"
        case .increaseLeft10: "Increase Left by 10%"
        case .increaseRight10: "Increase Right by 10%"
        case .increaseTop10: "Increase Top by 10%"
        case .increaseBottom10: "Increase Bottom by 10%"
        case .decreaseLeft10: "Decrease Left by 10%"
        case .decreaseRight10: "Decrease Right by 10%"
        case .decreaseTop10: "Decrease Top by 10%"
        case .decreaseBottom10: "Decrease Bottom by 10%"
        case .moveUp10: "Move Up by 10%"
        case .moveDown10: "Move Down by 10%"
        case .moveLeft10: "Move Left by 10%"
        case .moveRight10: "Move Right by 10%"
        }
    }
}
